version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  manylinux2014-aarch64:
    parameters:
      cibw_build:
        type: string
        default: "cp37-*"

    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
   
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: py_version
          command: |
            python --version
      - run:
          name: Install dependencies
          command: |
             bash -exc 'apt-get update && apt-get -y install python3 python3-pip python3-venv curl 
             python3 -m pip install virtualenv && python3 -m venv py38-venv 
             source py38-venv/bin/activate 
             python3 -m pip install --upgrade pip
             python3 -m pip install pytest
             python3 -m pip install pytest-asyncio 
             pip3 install -r requirements.txt
             python3 setup.py install
             cd tests
             pytest
workflows:
  version: 2.1
  main:
    jobs:
      - manylinux2014-aarch64:
          matrix:
            parameters:
              cibw_build:
                - "cp37*"
