version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  manylinux2014-aarch64:
    parameters:
      cibw_build:
        type: string
        default: "cp37-*"

    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
   
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: Install dependencies
          command: |
             apt-get update && apt-get -y install python3 python3-pip 
             python setup.py install
             pip install -r requirements-test.txt
             make install
              make test
workflows:
  version: 2.1
  main:
    jobs:
      - manylinux2014-aarch64:
          matrix:
            parameters:
              cibw_build:
                - "cp37*"
